src/locale/it.ts
src/pages/partySelectionContainer/NoParty.tsx

Co-authored-by: loremedda <lorenzo.medda.sa@nttdata.com>

SELC-1293 fix to style (#268)

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx
src/pages/partySelectionContainer/partySelection/PartySelection.tsx

Co-authored-by: loremedda <lorenzo.medda.sa@nttdata.com>

SELC-1330 using stack component rather than grid when we manage with buttons

---

.devops/deploy-pipelines.yml

Co-authored-by: anttorre <antonio.torre@everis.com>

SELC-1392 enabling assistance in PROD (#278)

---

openApi/dashboard-api-docs.json
package.json
src/model/Product.tsx
src/model/__tests__/Product.test.ts
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
src/services/__mocks__/productService.ts
yarn.lock

* SELC-1261 - update mui-italia version
* SELC-1261 - update openApi
* SELC-1261 -  updated card logo with ProductAvatar component
* SELC-1261 - updated with review changes
* SELC-1261 - fixed test

SELC-1261 update logo with product avatar

---

package.json
yarn.lock

update common and mui at the last version

---

openApi/dashboard-api-docs.json

* SELC-1412 - updated with last openApi
* SELC-1412 - updated with last openApi
Co-authored-by: fp <federico.piacitelli@everis.com>

SELC-1412 - updated with last openApi

---

CODEOWNERS
openApi/dashboard-api-docs.json
package.json
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/components/PartyDescription.tsx
yarn.lock

Release uat

---

src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/PartyLogoUploader.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/components/PartyDescription.tsx

SELC-1454 Removed unused logic and improve the actual

---

package.json
yarn.lock

+ Update common dependence at the most recent version

SELC-1404 Switch "Area Riservata" - BO Prodotto: se torno indietro vedo il nome del prodotto al posto di "Area Riservata"

---

src/components/partySelectionSearch/PartySelectionSearch.tsx

Keep automatic selection but removing "selection effect" and hover when partyList have only one choice

SELC-1511 Dashboard - scelta ente post login - unico ente collegato: rimozione effetto UI selezione

---

src/components/partySelectionSearch/PartySelectionSearch.tsx

SELC-1511 Removing "selection effect" and hover when partyList have only one choice

---

src/hooks/useTokenExchange.ts

SELC-1512 setting urlBO as possible undefined data

---

src/hooks/useTokenExchange.ts

setting as possible undefined data

---

src/components/partySelectionSearch/PartyItemContainer.tsx
src/components/partySelectionSearch/__tests__/PartySelectionSearch.test.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSidenavItem.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/components/PartyLogo.tsx

* SELC-1640 fix duplicated id
* SELC-1641 add missing alt to img
* SELC-1642 fix ul li correct hierarchy

SELC-1640 SELC-1641 SELC-1642

---

src/locale/it.ts
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx

Change in text of intermedia popup

---

package.json
src/pages/dashboard/Dashboard.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
yarn.lock

SELC-1006 Fix semantic structure HTML5 in order to obtain the recommended best pratice for accessibility

---

src/components/partySelectionSearch/__tests__/PartySelectionSearch.test.tsx
src/model/__tests__/Party.test.ts

* Add more unitTest in order to reach high coverage
* temp commit

Increase test coverage

---

openApi/dashboard-api-docs.json
src/api/__mocks__/DashboardApiClient.ts
src/model/Party.tsx
src/model/__tests__/Party.test.ts
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts

* SELC-1826 Added recipientCode field in the party overview
* SELC-1826 Update openApi + print the recipient code on the dashboard overview
* SELC-1826 temp commit
* SELC-1826 Resolved broken unitTest

SELC-1826 Added recipientCode field in the dashboard party overview

---

src/components/DashboardHeader.tsx
src/hooks/useTokenExchange.ts
src/locale/it.ts
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/__tests__/ActiveProductCard.test.tsx

…production problems"
This reverts commit 7db2db8dc4db52ddb1568a06d3996907d0d82ddd.

Revert "SELC-2009"

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/locale/it.ts
src/model/Party.tsx
src/model/__tests__/Party.test.ts
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts

* SELC-2025 temp commit
* SELC-2025 -  resolved bugs
* SELC-2025 - fixed unit tests
---------

SELC-2025 - added new fields to dashboard overview

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/model/Product.tsx
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx

* SELC-2263 - added premium flow in dashboard overview
* SELC-2263 - added bold in premium title
* SELC-2263 - added new api in order to show correct image and logo in premium card
* SELC-2263

SELC-2263-added premium card in not active product section (#472)

---

.github/PULL_REQUEST_TEMPLATE.md
package.json
yarn.lock

* Bump version to 1.4.0 [skip ci]
* Bump version to 1.5.0 [skip ci]
* Bump version to 1.6.0 [skip ci]
* Update CODEOWNERS
* docs: add pull request template
* SELC-2533 - updated common and mui last version in order to allow onboarding of name and surname with dash character
* SELC-2533 - updated common and mui last version in order to allow onboarding of name and surname with dash character
* SELC-2552-added-new-characters-acceptes
* updated common versione
---------
Co-authored-by: pagopa-github-bot <>

Merge back from main (#516)

---

package.json
src/model/Party.tsx
yarn.lock

Updating of the mui-italia library version in order to obtain the new changes to the ProductAvatar component

SELC-2531 Updating of the mui-italia library version in order to obtain the new changes to the ProductAvatar component

---

package.json
yarn.lock

Updated common version

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
package.json
src/api/DashboardApiClient.ts
src/components/DashboardHeader.tsx
src/components/partySelectionSearch/PartyAccountItemSelection.tsx
src/components/partySelectionSearch/PartyItemContainer.tsx
src/components/partySelectionSearch/PartySelectionSearch.tsx
src/model/GeographicTaxonomy.ts
src/model/Party.tsx
src/model/Product.tsx
src/model/__tests__/Party.test.ts
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/partyCard/components/GeoTaxonomySection.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/PartyLogoUploader.tsx
src/pages/partySelectionContainer/NoActiveParty.tsx
src/services/productService.ts
src/services/tokenExchangeService.ts
yarn.lock

add parent party name in switch and in party list in dashboard

SELC-2590 add ec on switch

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/api/DashboardApiClient.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/services/partyService.ts

Sending the name of the tech partner in submit API call
After a change in API call, we send also the name of the tech partner

SELC-2774 Sending the name of the tech partner in submit API call

---

src/api/DashboardApiClient.ts
src/locale/it.ts
src/model/Delegations.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/__tests__/Dashboard.test.tsx
src/pages/dashboardDelegations/DashboardDelegationsPage.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/services/delegationServices.ts
src/utils/constants.ts

added list of delegations in delegation page

SELC-2640-added delegations list

---

src/locale/it.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

Added a custom message error in case of already delegated techPartner

Custom message error in case of already delegated techPartner

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/pages/dashboardOverview/DashboardOverview.tsx

Release in dev environment of:
* Showing the banner for all institutionTypes
* Updated openApi in order to read correctly the new errorCode
The first point fixes a present bug, the second instead causes the codegen tool in its generation to recognize the 409 as a possible error of the call, which allows you to make logic to show the customized message

Showing the banner for all institutionTypes + updated openApi in order to read correctly the new errorCode

---

src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/services/__mocks__/productService.ts

Interop and interop-coll cards will only be shown if you are authorized to operate the product
With the above condition, if you are not authorized to operate on interop but are authorized to operate on interop-coll, both cards were displayed (including interop). With the new change, if you are not authorized to operate on interop, only interop-coll will be displayed

Interop and interop-coll cards will only be shown if you are authorized to operate the product

---

src/components/DashboardHeader.tsx
src/hooks/useSelectedParty.tsx
src/model/Party.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/partyCard/__tests__/PartyCard.test.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/routes.tsx
src/services/__mocks__/partyService.ts
src/services/__mocks__/productService.ts

Fixed some anomalies following the refactoring of the APIs called on the dashboard
In order to preserve functionality, these fixes have been implemented

Fixed post refactor dashboard regressions

---

src/pages/dashboardOverview/DashboardOverview.tsx

The banner is shown only for products that can be delegated

The banner is shown only for products that can be delegated

---

src/api/DashboardApiClient.ts
src/locale/it.ts
src/model/DelegationResource.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/__tests__/Dashboard.test.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTableContainer.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTechnologyPartnerPage.tsx
src/pages/dashboardTechnologyPartnerPage/TechnologyPartnerTable.tsx
src/routes.tsx
src/services/__mocks__/partyService.ts
src/services/technologyPartnerService.ts

added technology partner table list

added Technology Partner Table to display parties list

---

src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx

fixed bug removing geotax modal and label from dashboard overview page, it type PT

SELC-2883 - removed modal and label geotax if institutionType is PT

---

src/api/DashboardApiClient.ts
src/locale/it.ts
src/model/DelegationResource.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTableContainer.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTechnologyPartnerPage.tsx
src/pages/dashboardTechnologyPartnerPage/TechnologyPartnerTable.tsx
src/routes.tsx
src/services/__mocks__/partyService.ts
src/services/technologyPartnerService.ts

* SELC-2789 - modified icon and localized label
* SELC-2789 - added table empty state message
* SELC-2789 - added Expand More button and added multiple product display for a single Brockerid
* SELC-2789 - added sort
* SELC-2789 -modified the code to reduce complexity
---------

added Technology Partner Table to display parties list (#549)

---

src/hooks/useProductsRolesMap.tsx
src/hooks/useTokenExchange.ts
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx

- Available products visible only to admin roles
- The filter show only the correct roles for active products
- The last VAT number entered in an onboarding is shown on the screen
In order to resolve some unwanted behavior, these fixes have been introduced

SELC-2971 Fixed some incorrect behavior

---

src/hooks/useProductsRolesMap.tsx
src/hooks/useTokenExchange.ts
src/locale/it.ts
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTableContainer.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTechnologyPartnerPage.tsx
src/pages/dashboardTechnologyPartnerPage/TechnologyPartnerTable.tsx

Release in UAT environment of:
- SELC-2971
- SELC-2849
In order to have the filter on the search page of the entities that have delegated the technological partner and to fix some bugs that emerged following the refactor

SELC-2971 SELC-2849

---

src/pages/dashboard/Dashboard.tsx

Release in UAT environment of Showed all onboarded products tab

Showed all onboarded products tab

---

src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx

Add missing search icon in input field
Disable filter and reset button if search field value is empty
page different from figma design
run app locally

SELC-2849 Add missing search icon

---

src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx

* SELC-2849_disable the reset filters button
* SELC-2849 test for the component
* removed debug()
Removed disable on filter button. added it on reset filter button
tested on dev

SELC-2849 remove disable buttons (#560)

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/__test__/DashboardOverview.test.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/utils/test-utils.tsx

SELC-2970 delegation banner visible for GSP , PSP , SCP
Banner not visible for some institutions types
Run locally with mocks and with real api calls

SELC-2970 banner visible for all institutions types

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/__test__/DashboardOverview.test.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts
src/utils/test-utils.tsx

SELC-2970
Delegation banner not visible for prod-pagopa
Test on dev

Release dev

---

src/pages/dashboard/Dashboard.tsx

removed  authorized check in active products in dashboard

SELC-2970 removed authorized after merge of dev

---

src/pages/dashboardDelegations/__test__/DashboardDelegationsPage.test.tsx
src/pages/dashboardOverview/__test__/DashboardOverview.test.tsx
src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx
src/setupTests.ts

Unit test delegation

---

src/locale/it.ts
src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/services/__mocks__/partyService.ts

SELC-3020 and no result found message in filter.
When the filter returned no results show a message and a reset button 
Run locally with moock api

SELC-3020 add message when filter returns nothing

---

src/pages/dashboard/Dashboard.tsx

Removed only the inactive products
In order to not show only the INACTIVE products, we add this in the filter

Removed only the inactive products

---

src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardOverview/DashboardOverview.tsx

Hide group and available products for PT institutionType
The requirement requires that group and available products for PT institutionType aren't visible

SELC-2787 Hide group and available products for PT institutionType

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTableContainer.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx
src/services/technologyPartnerService.ts

Release in UAT environment of:
- SELC-3020 Hide show more button when no results
- SELC-2787 Removed only the inactive products
- Hide group and available products for PT institutionType
test with locally execution and with environment DEV data

SELC-3020 SELC-2787

---

src/pages/dashboardDelegations/DashboardDelegationsPage.tsx
src/pages/dashboardDelegations/__test__/DashboardDelegationsPage.test.tsx

Removed error page in case fetch delegation api return 200 with empty array
Fixed unexpected error page

Removed error page in case fetch delegation api return 200 with empty array

---

src/locale/it.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx

Hide delegation section
Delegation section is available only for institutionType different from PT, with delegable products and feature flag activated

Hide delegation section

---

src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/services/__mocks__/partyService.ts

Improvement in logic and cover missed business case
Improvement in logic with cleaner code and also cover missed business case
with mocks already present and the added one, test with dev environment data

Improvement in logic and cover missed business case

---

src/locale/it.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/services/__mocks__/partyService.ts

Release in UAT enviroment of improvement logic for active card showing (specifically for interop/interop-coll)

Improvement in logic active product card and cover missed business case

---

src/locale/it.ts
src/pages/dashboardOverview/__test__/DashboardOverview.test.tsx
src/services/__mocks__/partyService.ts

SELC-3068 new SA type 
Adapt dashboard page to render the label for the new SA institution type
Tested locally with mocked service

SELC-3068 add SA type in dashboard

---

src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx

Fixed addDelegation with dynamic institutionType and redirect to premium product
Given the opening to entities other than PT, the institutionType passed to the API call to retrieve the list in the delegation addition is no longer fixed PT but can be dynamic.
The premium card will redirect you to the premium product and no longer to the basic one
Started in local the repo and aiming in environments

Fixed addDelegation with dynamic institutionType + redirect to premium product

---

src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/__test__/DashboardOverview.test.tsx

SELC-3076 hide avaible products section for SA
Private SA can only onboard on interop. Need to hide other avaible products

SELC-3076 hide avaible products section for SA

---

src/pages/dashboardOverview/DashboardOverview.tsx

fix avaible products

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx

Added base product before premium

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/api/DashboardApiClient.ts

Update openApi in order to take SA enum value

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/api/DashboardApiClient.ts
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx

Updated openApi with the most recent version for take SA enum value

---

src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts

Hide geographic area in dashboard for SA
For private SA its not neccesary to show geographic are field in dashboard
Tested locally with moocked api

hide geographic area in dashboard for SA

---

src/components/DashboardHeader.tsx

Disabled the assistanceButton in the header only for UAT environment
In order to not allow users to send requests for support in a UAT environment

SELC-3084 Disabled the assistanceButton in the header only for UAT environment

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardDelegations/DashboardDelegationsPage.tsx
src/services/__mocks__/partyService.ts

SELC-3023 hide product in delegation page if not authorized
The user should not be able to add delegation on a product where its not authorized

SELC-3023 Hide product in delegation page for not authorized

---

src/pages/dashboardDelegations/DashboardDelegationsPage.tsx
src/services/__mocks__/partyService.ts

* SELC-3023 hide product in delegation page for not authorized
If the institution is not authorized to delegate on the product it should not be visible in the delegation page.

SELC 3023 Hide product in delegation page for not authorized institutions

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardDelegations/DashboardDelegationsPage.tsx
src/pages/dashboardDelegations/__test__/DashboardDelegationsPage.test.tsx
src/pages/dashboardDelegationsAdd/AddDelegationPage.tsx
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

* SELC-3023_hide not authorized products in the add delegation form
The not authorized products should not be visible in the select options in Add delegation form
Tested in dev

SELC-3023_hide not authorized products in the add delegation form

---

src/pages/dashboard/Dashboard.tsx

SELC-3023_hide delegated products if  userRole not admin
If the user role in the producet is not Admin you should not be able to delegated it.

SELC-3023_hide delegated products if  userRole not admin

---

.devops/deploy-pipelines.yml
package.json
src/components/partySelectionSearch/__tests__/PartySelectionSearch.test.tsx
src/locale/it.ts
src/pages/partySelectionContainer/NoActiveParty.tsx
src/pages/partySelectionContainer/PartySelectionContainer.tsx
src/services/__mocks__/partyService.ts
yarn.lock

Managed tobevalidated party in selection party page and modified deploy yml
In order to show an outcome different from popup not manageable

SELC-2757 Managed tobevalidated party in selection party page + modified deploy yml

---

.devops/deploy-pipelines.yml
package.json
src/components/ProductNavigationBar.tsx
src/components/partySelectionSearch/__tests__/PartySelectionSearch.test.tsx
src/locale/it.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboardDelegationsAdd/AddDelegationPage.tsx
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/pages/partySelectionContainer/NoActiveParty.tsx
src/pages/partySelectionContainer/PartySelectionContainer.tsx
src/services/__mocks__/partyService.ts
yarn.lock

- SELC-2757 Managed tobevalidated party in selection party page + modified deploy yml
- SELC 3127 change layout of page add delegation
Release of the new worked feature
With locally starting and aiming dev environment

SELC-2757 SELC 3127

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

* SELC-3127 removed console.log
* SELC-3127 fontSize change of title

SELC 3127 remove console.log

---

package.json
src/components/DashboardHeader.tsx
src/utils/env.ts
yarn.lock

SELC-3135 add documentation button in header
Update common library
Tested in dev

SELC-3135 update common and add documentation button in header

---

package.json
yarn.lock

SELC-3242 updated common library
updated the common library to version 1.34.11

SELC-3242 updated common library

---

package.json
yarn.lock

SELC-3242 updated common library to version 1.34.11
Keep common updated after translation files changes in the library

SELC-3242 updated common library to version 1.34.11

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
openApi/generated-party-registry-proxy/party-registry-proxy-swagger20.json
openApi/party-registry-proxy-api-docs.json
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts

Update the opeApi for institutionType AS
Remove GeoTaxModal for AS
New institution type added AS (insurance companies) need to update openApi for codegen

Update open api for institution type AS

---

src/locale/it.ts

SELC-3239 add new label in dashboard pagefor instituton type AS
Render new label for insurance companies
Tested locally

[SELC-3239 ] feat: Add new label for AS

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
openApi/generated-party-registry-proxy/party-registry-proxy-swagger20.json
openApi/party-registry-proxy-api-docs.json
src/locale/it.ts
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts

SELC-3239 add new label for AS
Update open api for institution type AS
Adapted the dashboard page to expect the new institution type AS 
Tested in dev enviroment

[SELC-3239] feat: Add new label for AS and update openAPI institutionType

---

src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/__test__/DashboardOverview.test.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx

SELC-3280 Hide available products for institutionType  AS (insurance companies)
Insurance companies can only onboard on prod-interop so the other products dont need to be visible
Tested with jest and by running the app in local

[SELC-3280] feat: Hide available products for institutionType AS

---

src/api/__mocks__/DashboardApiClient.ts
src/model/Party.tsx
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts

Fix geographic taxonomy
Checked existance of geographicTaxonomy, now the cases of existence of the geographic Taxonomy as well as the empty of the array have been covered
Aiming DEV environment data, if the geographicTaxonomy property is undefined, dashboard works and popup for add new geotaxonomy is open correctly

fix: Fix geographic taxonomy

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/locale/it.ts
src/model/Product.tsx
src/model/__tests__/Product.test.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/__tests__/Dashboard.test.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/services/__mocks__/partyService.ts
src/services/__mocks__/productService.ts

Show Invoice button in side menu for products that are invoicable.
Update swagger of dashboard.
If a user has a role in a product thats is invoiceable the user should be able reach Invoice portal by clicking on the side menu button.
Tested in dev enviroment

[SELC-3406] feat: Show in side menu button for invoiceable products

---

src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/routes.tsx

Sorting institutions list for PT alphabetically
In dashboard PT view allow the user to order the institutions list in alphabeticall order by pressing the arrow icon above the institution name.
Tested in local enviroment with mocked data.

[SELC-3003] fix: Sorting institutions list for PT alphabetically

---

src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx

Sorting institutions list for PT alphabetically
Motivation and Context
In dashboard PT view allow the user to order the institutions list in alphabeticall order by pressing the arrow icon above the institution name.

[SELC-3003] fix: remove search on select

---

src/locale/it.ts

In add delegation page change label for select tech partner and intermediaries
tested locally.

[SELC-3466] feat: change label for select tech partner and intermediaries

---

src/locale/it.ts

In add delegation page change label for select tech partner and intermediaries

[SELC-3466]  feat: change label for select tech partner and intermediaries

---

src/api/__mocks__/DashboardApiClient.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

Improved alphabetical order only considering letters
Added a logic for considering only alphabetical ignoring character different

[SELC-3477] feat: Improved alphabetical order only considering letters

---

src/api/__mocks__/DashboardApiClient.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

Alphabetically ordereded productBrokers list
In order to resolve productBrokers list order, now is alphabetically
Tested in DEV environment, the brokers are correctly in alphabetically order

[SELC-3477] feat: Alphabetically ordereded productBrokers list

---

src/api/__mocks__/DashboardApiClient.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

[SELC-3477] feat: Cleaned code + lower case strings

---

src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/services/__mocks__/partyService.ts

Temporary hide pagopa product card from available product for payment service providers + mock cases
The pagopa product card is not shown in the available products as the possibility for payment service providers to join the product has been temporarily suspended
Created some cases and tested in local environment

feat: Temporary hide pagopa product card from available product for payment service providers + mock cases

---

src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/services/__mocks__/partyService.ts

Hide pagopa product card from available product for payment service providers + mock cases
In order to temporary hide the product card of product pagopa from available products only for payment service providers
Tested in DEV environment

feat: Hide pagopa product card from available product for payment service providers + mock cases

---

src/api/DashboardApiClient.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

Removed delegates based brokerName nor id
In order to cover some changes in response from API backoffice, was introduced a more flexible filter based to brokerName

feat: Removed delegates based brokerName nor id

---

src/api/DashboardApiClient.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx

Removed delegates based brokerName nor id
In order to cover some changes in response from API backoffice, was introduced a more flexible filter based to brokerName

feat: Removed delegates based institutionName nor id

---

package.json
yarn.lock

Update commons library to version 1.34.12
Change footer label privacy policy

[SELC-1712] feat; Update commons library to version 1.34.12

---

src/locale/it.ts
src/services/__mocks__/partyService.ts

New translation label for institutionType PG
in order to visualizze the label in dashboard for institutionType  = PG 
tested locally

[SELC-3568] feat: New translation label for institutionType PG

---

src/components/DashboardHeader.tsx

Added mixpanel event for open operative manual
In order to make analytics with opening operative manual, the event contains the from property which will be valorised with the point of the application from which the manual is accessed (onboarding/login/dashboard)
Local

[SELC-3585] feat: Added mixpanel event for open operative manual

---

src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx
src/services/__mocks__/partyService.ts

Unit tests for side menu component

---

src/index.css

Overwrite the style of cookie baneer to Tittillium web

[SELC-1294] feat: change font family of cookie banner

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx

Hide name in add delegation form select pt combobox 
unit tests for AddDelegationform
The inermediated entities data for is not avaible at the moment so as requested by UX we should hide Name header in combobox select PT
Tested locally

[SELC-3833] feat: hide name until intermediated entities data is avaible.

---

package.json
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
yarn.lock

updated common-fe library dependency at v1.34.14
In order to maintain align the versions of common-fe dependency between orchestrator and MF

feat: updated common-fe library dependency at v1.34.14

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/pages/dashboard/Dashboard.tsx

Once you select an Instititution of type PT you should be rendered in the "your institution page" not overview page

[SELC-3843] feat: Dynamic rendering of dashboard page for PT

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/locale/it.ts

Updated open api
In order to take updated resource (particulary the institutionTypeEnum)

feat: Updated openApi and added REC and CON labels

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx

* SELC-2278 add mix panel event for PREMIUM_CTA_JOIN
In order to track the user when he onboards from dashboard to prod-io-premuim
Tested in dev

[SELC-2278]: Feat: Integration with mix panel events for premium flow

---

src/pages/dashboard/Dashboard.tsx

fix: fixed typo

---

src/components/DashboardHeader.tsx
src/locale/it.ts
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/GenericEnvProductModal.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/SessionModalInteropProduct.tsx
src/services/__mocks__/partyService.ts
src/services/__mocks__/productService.ts

Added a new modal ui when switching enviroments and integrated new enviroment for interop Attestazioni.
In order to follow new style guidelines and to enable users of product interop to enter the new enviroment of prod-interop-atst
Tested locally and by aiming at dev data.

[SELC-4361] Feat: Integrated new enviroment for prod interop and new modal for switch enviroment

---

src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx

Added L15 and C14 in allowed categories
In order to open the onboarding on product SEND to 2 new categoris.

[SELC-4453] Feat: allow categories L15 and C14 to onboard in SEND

---

src/components/DashboardHeader.tsx

In order to show interop in menu in header
Tested locally

Fix show interop in header menu

---

src/components/DashboardHeader.tsx
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/SessionModalInteropProduct.tsx

corrected when to show the modal of interop attestazino
The card interop should be shown if not authorized on prod but still authorized in collaudo e attestazioni.
Tested locally

[SELC-4361] Fix: correct mangment of show modal interop

---

src/components/DashboardHeader.tsx

hide documentation button
The documentation of selfcare at the moment is only in italian so it should not be avaible to other languages
Tested locally

[SELC-4492] Feat: hide documentation link for non italian language

---

src/components/DashboardHeader.tsx
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/SessionModalInteropProduct.tsx

hide documentation button
The documentation of selfcare at the moment is only in italian so it should not be avaible to other languages
Tested in dev

[SELC-4492] Feat: hide documentation button for non italian language

---

src/locale/it.ts

typo in modal label

---

src/components/DashboardHeader.tsx
src/pages/dashboard/Dashboard.tsx

Change landing page redirect
Tested locally

[SELC-4586] Feat: Change landing page for institutions that can be delegated

---

src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts

feat: Removed duplicated code+added mock use case

---

src/bootstrap.tsx

added spinner in case of getInstituions is loading
To improve the user expierence when the user enters in dashboard.
Tested locally

[SELC-4604] Fix: add feedback when get institutions in loading

---

src/locale/it.ts
src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx

Changed copy to follow new figma design
Tested locally

[SELC-4778] Feat: adapt add delegation page copy to new figma design

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/locale/it.ts
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx

- Added radio buttons institution name and fiscal code
- Update swagger dashboard
- Change autocomplete label 
While creating a delegation to allow to search by instituion name or by fiscal code added a raddio button to allow the switch.
Tested locally and unit test

[SELC-4780] Feat: add search by fiscal code radio button

---

.devops/deploy-pipelines.yml
.env.development.local
.env.test.local
src/model/CountryResource.ts
src/model/Party.tsx
src/model/__tests__/Party.test.ts
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts
src/utils/env.ts

Render fields city and country
integrate api to get nations list
In order to show the fields city and country for foreign insurance companies.
Tested by deploying branch in dev

[SELC-4831] Feat: render in dashboard city and country for foreign insurance

---

.devops/deploy-pipelines.yml
.env.development.local
.env.test.local
src/model/CountryResource.ts
src/model/Party.tsx
src/model/__tests__/Party.test.ts
src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx
src/services/__mocks__/partyService.ts
src/utils/env.ts

[SELC-4831] Feat: render in dashboard city and country for foreign insurance
Tested in dev
[SELC-4831]: https://pagopa.atlassian.net/browse/SELC-4831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4831] Release UAT

---

src/locale/it.ts
src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx

change copy to fit figma.
adapt unit tests
Tested locally.

[SELC-4880] Feat: change copy of your instituions page

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/api/DashboardApiClient.ts
src/api/__mocks__/DashboardApiClient.ts
src/decorators/__tests__/withSelectedParty.test.tsx
src/locale/it.ts
src/model/Product.tsx
src/model/TechnologyPartner.ts
src/model/__tests__/Product.test.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTableContainer.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTechnologyPartnerPage.tsx
src/pages/dashboardTechnologyPartnerPage/TechPartnersTable.tsx
src/pages/dashboardTechnologyPartnerPage/TechnologyPartnerTable.tsx
src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx
src/pages/dashboardTechnologyPartnerPage/components/EmptyFilterResults.tsx
src/services/__mocks__/productService.ts
src/services/__tests__/partyService.test.ts
src/services/partyService.ts
src/services/technologyPartnerService.ts
src/services/tokenExchangeService.ts

Modified the search functionality to allow filtering by institution name and ID.
Removed the option to search by product.
Updated the UI elements to reflect the new search options.
The previous search functionality limited filtering options, making it more difficult for users to find specific institutions.
Enabling name and ID searches provides greater flexibility and improves the efficiency of finding desired institutions.
Manual testing was conducted to verify the UI updates and overall user experience

[SELC-4915] Feat:  Enhance search functionality: Enable name and tax code search.

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/__tests__/NotActiveProductCard.test.tsx

Cherry-pick for dynamic query params for io premium, this [PR](https://github.com/pagopa/selfcare-dashboard-frontend/pull/737)

[SELC-4969] cherry-pick: dynamic query params for io premium

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/__tests__/NotActiveProductCard.test.tsx

added check for baseProductWithExistingSubProductNotOnboarded 
fixed unit tests

[SELC-4915] hotfix: During onboarding redirect send partyExternalID for app-io and partyId for app-io-premium

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/__tests__/NotActiveProductCard.test.tsx

[[SELC-4915] hotfix: During onboarding redirect send partyExternalID]
To release in production enviroment the worked features.
[SELC-4915]: https://pagopa.atlassian.net/browse/SELC-4915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release Prod

---

src/locale/it.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx
src/pages/dashboardOverview/components/partyCard/__tests__/PartyDetail.test.tsx
src/pages/dashboardTechnologyPartnerPage/TechPartnersTable.tsx
src/pages/dashboardTechnologyPartnerPage/TechnologyPartnerTable.tsx
src/services/__mocks__/partyService.ts
src/services/__mocks__/productService.ts
src/services/technologyPartnerService.ts

PT should always se PT page
other type of institutions only see it if they are admin on delegable product and have an active delegation
In order to handle when the PT page is visible based on user role, instition type and 
Tested locally

[SELC-4884]  Fix: The PT page only visible for admin in delegable product or for PT

---

src/components/partySelectionSearch/PartyItemContainer.tsx
src/components/partySelectionSearch/PartySelectionSearch.tsx
src/pages/dashboardTechnologyPartnerPage/TechPartnersTable.tsx
src/pages/dashboardTechnologyPartnerPage/components/TableCellWithTooltip.tsx

add tag of type info for toBeValidated
add tag of type warning Pending 
To help the user distinguish between the two types

[SELC-4572] Feat: tag to distinguish between Pending and toBeValidated

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx

Made App io and Premium have diffent css styles
To follow figma design
Tested locally

Feat: changed style for io premium name

---

package.json
yarn.lock

updated selfcare commons version
To read from url query params the lang
Tested in local environment setting the language on the query parameter, the portal language changes and the correct language is selected in the switch on the footer

[SELC-5002] Feat: Predisposition for reading the language from query paramete

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSidenavItem.tsx
src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx

changed the layout of the sidebar to be responsive
To update the FE with the new responsive design from MUI design.
Tested locally

[SELC-5027] Feat: responsive layout for sidebar 

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSidenavItem.tsx
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx

Added button to close the menu of the sidebar
Tested locally

[SELC-5027]Feat: add button to close side bard and update swagger

---

package.json
yarn.lock

update mui library version
To get the new color styles for chip and tag components

[SELC-4552] Feat: update mui italia library

---

src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx

removed not neccesary personalized Chip colors style

[SELC-4552]  remove personalized chip colors

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/pages/dashboardOverview/components/partyDetailModal/DashboardInfoBanner.tsx

changed product card design for prod-io-premium
get the correct logo for prod-io-premium
To adapt the design of the product card.
Tested by aiming at uat enviroment data

[SELC-5130] Feat: adapt product Card to design

---

src/locale/it.ts
src/pages/partySelectionContainer/NoParty.tsx
src/services/partyService.ts

Add link to Roles documentation
Add link to the new add admin page.
To allow a user without any active institions assiociated with him to add a new admin.
Tested locally

[SELC-4356] Feat: Add links to user Role doc and add admin flow

---

package.json
yarn.lock

update the mui italia library to get the new drawer

[SELC-4585] Feat: Update mui italia library

---

package.json
src/components/ProductNavigationBar.tsx
src/pages/dashboardDelegationsAdd/AddDelegationPage.tsx
yarn.lock

update coomon library
update mui itlaia
change breadcrumb design
Tested locally

[SELC-4547] feat: responsive breadcrumb in delegation page

---

src/locale/it.ts
src/pages/dashboardDelegations/DashboardDelegationsPage.tsx

[SELC-4548 add link to documentation](https://github.com/pagopa/selfcare-dashboard-frontend/commit/63618dd8e581ff5d99a252afb834d364218fa99b)
To allow the user to read about what is a delegation.
Tested locally

[SELC-4548] feat: Add link to documentation for delegations

---

src/locale/it.ts
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx

We have recently updated our product interface to remove the link to users under the "Administrators" section for not authorized products. This change was implemented to streamline the user experience and ensure clarity in product management.
To adapt the ui for the new user roles policy
Tested locally

[SELC-5292] feat: Update to Remove User Link in "Administrators" on not authorized Product Card

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
package.json
src/components/DashboardHeader.tsx
src/hooks/useSelectedParty.tsx
src/locale/it.ts
src/model/Party.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/__tests__/Dashboard.test.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSidenavItem.tsx
src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx
src/pages/dashboardDelegations/__test__/DashboardDelegationsPage.test.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/pages/dashboardOverview/components/partyDetailModal/PartyDetailModal.tsx
src/pages/dashboardTechnologyPartnerPage/DashboardTechnologyPartnerPage.tsx
src/redux/store.ts
src/services/__mocks__/partyService.ts
src/setupTests.ts
yarn.lock

Adapt pnpg dashboard to hadnle authorizations with the actions
updated the swagger
update common library
In order to have a better more scalable handling of the user roles and actions.
Tested in dev

[SELC-5161] feat add permission reducer and adapt permissions logic

---

package.json
yarn.lock

[SELC-5303] feat: Updated selfcare-common library dependency
In order to keep the common library dependency up to date
[SELC-5303]: https://pagopa.atlassian.net/browse/SELC-5303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5303] feat: Updated selfcare-common library dependency

---

src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx
src/services/__mocks__/partyService.ts
src/services/__mocks__/productService.ts

changed active products card layout
changed icon for overview sidebar
small style fixes
To adapt the page to the figma design
Tested locally

[SELC-4862] feat: change layout of overview page

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx

Show tooltip when the product description is truncated
Tested loaclly

[SELC-5354] feat: product description visible when truncated text

---

src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
src/pages/dashboardOverview/components/partyCard/components/__tests__/GeoTaxonomySection.test.tsx

unit tests for Add delegation form component
unit tests for geo tax section component
To increase coverage of tests
Tested by runing tests locally

Unit tests for add delegation and geoTaxSection

---

src/pages/dashboard/Dashboard.tsx

Hide the side bar for add users page
To update the design of the page as in figma.
Tested in local enviroment

[SELC-5367] Feat: hide side bard for add users page

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/api/DashboardApiClient.ts
src/api/__mocks__/DashboardApiClient.ts
src/model/ProductRole.ts
src/model/__tests__/Party.test.ts
src/model/__tests__/ProductRole.test.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
src/services/__mocks__/productService.ts
src/services/__tests__/partyService.test.ts
src/services/partyService.ts
src/services/productService.ts
src/services/technologyPartnerService.ts

updated open api
updated mocks
removed institution type enum
Its necessary to update the open api for the codegen validation.
Tested but running unit tests.

[SELC-5618] Feat: Update swagger for EA and institution enum

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
package.json
yarn.lock

changed api path of geographic-taxonomy
updated swagger 
updated selfcare commons library
The old api was deprecated so the new one was added
Tested by calling the api

[SELC-5644] Feat: changed path of api geographic-taxonomy

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/locale/it.ts
src/model/Party.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx
src/services/__mocks__/partyService.ts

updated dashboard swagger
changed condition to allow aggregators to se handle delegation page
added unit tests
changed mock data
An instituion of tye aggregator is allowed to see the page handle delegation even if the product onboarded is not a delegable product.
Tested in local enviroment with mocked data and unit tests

[SELC-5699] Feat: Instituions of type EA can hadle delegation

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/api/DashboardApiClient.ts
src/api/__mocks__/DashboardApiClient.ts
src/decorators/withSelectedPartyProduct.tsx
src/hooks/__tests__/useProductRoles.test.tsx
src/hooks/useProductRoles.tsx
src/hooks/useProductsRolesMap.tsx
src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx
src/services/__mocks__/productService.ts
src/services/__tests__/productService.test.ts
src/services/productService.ts

Added institution type to roles api
changed mocks data 
fixed unit tests
The product pagopa hase different label for the role when adding a new user. 
Tested by aiming at dev data

[SELC-5637] Feat: Add institution type to roles api

---

package.json
yarn.lock

updated selfcare commons library

SELC-5650 updated selfcare commons

---

package.json
yarn.lock

Added fix for security vunerability on body-parser dependency 
updated selfcare commons library
To fix security vulnerability
yarn audit

[SELC-5660] fix for security vulnerability on body parser 

---

src/pages/dashboardDelegations/DashboardDelegationsPage.tsx
src/pages/dashboardTechnologyPartnerPage/TechPartnersTable.tsx
src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx
src/pages/dashboardTechnologyPartnerPage/__tests__/utils.test.ts
src/services/productService.ts
src/services/technologyPartnerService.ts

Removed hard coded product name in handle delegations page
Read product title from products configuration
updated unit tests
The products name should be read from the same source everywhere in dashboard and not be hard coded in the FE.
Tested by running the application locally

[SELC-5724] Feat: In Handle delegations page read product title in products configuration json

---

src/pages/dashboard/Dashboard.tsx

Temporarly hide sidebar for users
To unblock the release in PROD

[SELC-5367] Temporarly hide sidebar for users

---

src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx

Simplified and fixed logic for interop in active products section
When onboarded but  not authorized on any enviroment multiple cards of interop were seen in active products section.
Tested by running application locally

[SELC-5791] Fix: Fixed interop logic for active product section

---

package.json
src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
yarn.lock

Update selfcare common library version
To update the version of the library to the same as the other dashboard FE
Tested in dev

[SELC-5842] Feat: update selfcare commons for new action

---

src/pages/dashboard/Dashboard.tsx

hidden again the sidebar for add users page
After release in Prod the add users page need to go back to a wizard format
Tested locally

[SELC-5370] Feat: hide the side bad for add users page

---

src/model/Party.tsx
src/model/ProductRole.ts
src/model/__tests__/ProductRole.test.ts
src/pages/dashboard/Dashboard.tsx

Add  mapping for ADMIN_EA in groupBySelcRole 
Add mapping form ADMIN_EA in groupByPartyRole
The users list page would break if the roles api returned ADMIN_EA as party Role
Tedted by deploying branch in dev

[SELC-5886] Fix: handle ADMIN_EA from roles api response 

---

src/pages/dashboardTechnologyPartnerPage/TechPartnersTable.tsx
src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx
src/services/__mocks__/partyService.ts

Add check if delegation is avaible in the getInstituions list 
add unit test
adapt mock Data 
The delegation should only be clickable if the same instituion is also present in the getInstituions list in the header menu.
Tested by running application locally and mocking data.

[SELC-5823] Feat: add check if delegation  is present in getInstituions list

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/__tests__/Dashboard.test.tsx
src/pages/dashboard/components/dashboardSideMenu/DashboardSidenavItem.tsx

Hidden sidebar for edit user detail page
add unit test to increase coverage
To adapt the page of user detail with the new figma design.
Tested by runing dashboard and user in local enviroment.

[SELC-5920] Feat: hide sidebar for edit user detail page

---

src/components/DashboardHeader.tsx
src/pages/dashboardDelegationsAdd/__tests__/AddDelegationPage.test.tsx
src/pages/dashboardOverview/__tests__/DashboardOverview.test.tsx
src/pages/dashboardOverview/components/__tests__/ActiveProductsSection.test.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx

fixed a bug where by clicking production you would be redirected to collaudo enviroment
unit tests
fix for bug 
Tested by mocking the uat enviroment in local with the user token from the ticket

[SELC-5888] Fix: rederict interop production enviroment

---

src/model/Product.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/__tests__/NotActiveProductsSection.test.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/productFilters.ts
src/services/__mocks__/productService.ts

Integrated new api
removed api call for categories
filter logic for notActiveProductSection
adapt unit tests
mocked resposne data
Integrated new configuration file to have e centralized and configurable place where to specify which instituions type can onboard on which product
Tested by mocking the dev enviroment data and running the application

[SELC-5966] Feat: integrate new file json with configuration for wich institutitions type can onboard

---

src/locale/index.ts
src/locale/it.ts
src/pages/dashboardOverview/components/welcomeDashboard/WelcomeDashboard.tsx

feat: added italian language fallback
So as not to show references to the translation file for languages ​​not yet translated. The change is temporary and will be removed when the agency makes the translations available
Tested in dev environment, all untranslated texts will have Italian as a fallback

feat: added italian language fallback

---

src/locale/index.ts

[SELC-5986] feat: Removed italian fallback and using the translations provided for each language
In order to provide the i18n library with the submitted translations for each language
Tested in dev environment, all the texts that were not translated were collected on another task
[SELC-5986]: https://pagopa.atlassian.net/browse/SELC-5986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5986] feat: Removed italian fallback and using the translations provided for each language

---

src/locale/de.ts
src/locale/en.ts
src/locale/fr.ts
src/locale/index.ts
src/locale/it.ts
src/locale/sl.ts
src/model/Product.tsx
src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/__tests__/NotActiveProductsSection.test.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/productFilters.ts
src/pages/dashboardOverview/components/welcomeDashboard/WelcomeDashboard.tsx
src/services/__mocks__/productService.ts

[SELC-5986] feat: Removed italian fallback and using the translations provided for each language
[SELC-5966] Feat: integrate new file json with configuration for wich institutitions type can onboard
[SELC-5996] Fix: filter on party id change
In order to provide the i18n library with the submitted translations for each language and release in uat the other worked features
Tested in dev environment, all the texts that were not translated were collected on another task.
As for the other features released, they have been tested in dev making sure that the required functionality is respected.
[SELC-5986]: https://pagopa.atlassian.net/browse/SELC-5986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5966]: …

SELC-5986 SELC-5966 SELC-5996

---

package.json
src/pages/dashboardHandleDelegatesPage/__tests__/DashboardHandleDelegatesPage.test.tsx
src/pages/dashboardHandleDelegatesPage/components/TableCellWithStyle.tsx
src/pages/dashboardHandleDelegatesPage/components/TechPartnersTable.tsx
src/pages/dashboardHandleDelegatesPage/components/TechnologyPartnerTable.tsx
src/pages/dashboardHandleDelegatesPage/components/__tests__/DashboardTablePT.test.tsx
yarn.lock

map instituionRootName in handle delegation page
remove not used dependecies
In case of aoo/uo the parent instition name should be rendered as well.
Tested in local by aiming at dev data

[SELC-5867] Feat: map instituionRootName for aoo/ uo

---

package.json
yarn.lock

Added resolution for node-fetch vulnerability
clean install of yarn lock
To resolve vulnerabilites warnings from dependebot

[SELC-5941] Feat:  Resolve vulnerability for node-fetch dependency

---

package.json
src/components/partySelectionSearch/__tests__/PartySelectionSearch.test.tsx
src/pages/dashboard/__tests__/Dashboard.test.tsx
src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx
src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
src/pages/dashboardHandleDelegatesPage/components/__tests__/DashboardTablePT.test.tsx
src/pages/dashboardOverview/__tests__/DashboardOverview.test.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/__tests__/GenericEnvProductModal.test.tsx
src/pages/dashboardOverview/components/activeProductsSection/components/__tests__/SessionModalInteropProduct.test.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/__tests__/NotActiveProductCard.test.tsx
src/pages/dashboardOverview/components/partyCard/components/__tests__/GeoTaxonomySection.test.tsx
yarn.lock

[SELC-6042] feat: Updated common-frontend library dependency for introduce language detection feature
In order to introduce the language detection feature
Tested in local environment ensuring that all the use case are satisfied
[SELC-6042]: https://pagopa.atlassian.net/browse/SELC-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6042] feat: Updated common-frontend library dependency for introduce language detection feature

---

package.json
yarn.lock

hotfix: regen yarn.lock + missing dependencies

---

src/locale/it.ts
src/services/__mocks__/partyService.ts
src/services/__mocks__/productService.ts

Added instituion type label for gpu
updated mock data
A new type of instituion is allowed to onboard on prod-pagopa. Updated the translation file to handle the new instituion type
Tested by running the application in local and mocking the data

[SELC-6075] Feat: Add GPU instituion type label in dashboard

---

src/bootstrap.tsx

Add missing path to login

---

e2e/playwright.config.ts
e2e/tests/access-product-backoffice.spec.ts
e2e/tests/can-acces-delegation.spec.ts
e2e/tests/can-acces-invoice-section.spec.ts
e2e/tests/change-geotaxonomy.spec.ts
e2e/tests/onboarding-new-product.spec.ts
e2e/utils/login.ts

Introduced a 500ms delay between actions for improved test visibility.
Ensured device-specific settings for Google Chrome remain intact while applying slowMo
Test delegations visibility
Test Invoice section visibility
Increase integration test coverage and improve testing expierence with slowMo

[SELC-6196] feat: update integration tests and configuration

---

src/pages/dashboardOverview/DashboardOverview.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/__tests__/productFilter.test.ts
src/pages/dashboardOverview/components/welcomeDashboard/WelcomeDashboard.tsx
src/services/__mocks__/partyService.ts

removed phone number banner
add unit test
The banner period has expires so it should be removed.

[SELC-6343] feat: Remove phone number banner

---

package.json
yarn.lock

chore:  update selfcare common frontend version

---

package.json
src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
yarn.lock

update selfcare common
Neccesary update of common version for the new link in the footer

[SELC-6417] feat: update selfcare commons for new link accesability

---

src/model/Party.tsx
src/model/ProductRole.ts
src/model/__tests__/ProductRole.test.ts
src/services/__mocks__/productService.ts

Add new PartyRole Admin Ea IO
updted unit test
updated mocked data

[SELC-6377] feat: hadle partyRole Admin_EA_IO in dashboard

---

yarn.lock

The frontend would take a long time (8 min) to start in local and build during deploy.

regenerate yarn lock from yarn registry 

---

src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/services/__mocks__/partyService.ts
src/services/__mocks__/productService.ts
src/utils/constants.ts

add premium label only for prod-io
add mocked data for local test
The new child product psp dashboard should have same name as parent product

[SELC-6518] feat:change name for psp dashboard product

---

src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx

Removed marign 8 px.
The margin was changing the on hover background shape.

[SELC-6541] feat: remove margin from icon button

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/productFilters.ts
src/utils/constants.ts

change of product id to prod-dashboard-psp

change prod id to prod-dashboard-psp

---

src/pages/dashboardOverview/DashboardOverview.tsx

Updated doc link
Banner only visible for io and io premium

updated documentation link

---

infra/repository/github_repository.tf

Add Repo Identity Federation

---

src/__tests__/App.test.tsx
src/decorators/__tests__/withParties.test.tsx
src/pages/dashboardDelegations/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/PartyLogoUploader.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/__tests__/PartyLogoUploader.test.tsx
src/pages/dashboardOverview/components/partyDetailModal/PartyDetailModal.tsx
src/redux/slices/partiesSlice.ts
src/services/__mocks__/partyService.ts
src/utils/__tests__/utils.test.ts
src/utils/helperFunctions.ts

add cache busting for logo
add hard reload on chage of logo
To fix an issue when ulpoading a new logo but the browser would still show the old one.

[SELC-6662] fix: add cache busting for url logo

---

src/pages/dashboardOverview/components/partyCard/components/PartyDetail.tsx

Removed useEffect what was updating party detail to much
Optimize code

removed unnecesary useEffect

---

src/pages/dashboardOverview/DashboardOverview.tsx

[SELC-6888] feat: Update link for IO groups

---

.github/workflows/create_release_branch.yml
.github/workflows/deploy_cdn.yml

Updated version of ubuntu LTS

---

src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
src/pages/dashboardDocuments/components/ProductCards.tsx
src/pages/dashboardDocumentsDetail/DashboardDocumentsDetailPage.tsx

Add 3 events to track user.
Gather analytics on user behaviour on dashboard documents section.

[SELC-6624] feat: Add mixpanel events to track user in dashboard documents

---

src/pages/dashboardOverview/DashboardOverview.tsx

removed banner for io groups in dahboard
removed logic to handle visibility of banner
The 45 days period has expired so the banner should be removed.

[SELC-6823] feat: remove banner io dashboard

---

src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx

For accesability reasons need text on the icon button

[SELC-7221] feat: add text to icon button

---

src/services/productService.ts

send institution type parameter based on the product

[SELC-7158] feat: enhance fetchProductRoles to use institution type from active onboardings

---

src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx

fix: update NotActiveProductCardContainer to improve PSP institutiontype handling

---

src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCard.tsx
src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/PartyLogoUploader.tsx
src/pages/dashboardOverview/components/partyCard/components/partyLogoUploader/components/PartyDescription.tsx
src/pages/dashboardOverview/components/partyDetailModal/PartyDetailModal.tsx

adjust layout card button
fix some semantic console warnings

refactor: adjust grid item properties for better layout consistency in multiple components

---

src/components/DashboardHeader.tsx
src/components/Layout/Layout.tsx
src/locale/it.ts
src/pages/dashboardOverview/components/partyDetailModal/components/GeoTaxonomySection.tsx

Implement on exit confirmation modal
To make sure the user does not accidentally exit wtihout confirming first.

[SELC-7274] feat: implement exit confirmation modal in DashboardHeader and update translations

---

src/components/DashboardHeader.tsx
src/locale/it.ts

removed interceptor 
add session modal

feat: add exit confirmation modal to DashboardHeader and update Italian translations

---

.github/workflows/code_review.yaml

chore: update workflow to run on Ubuntu 24.04

---

package.json
yarn.lock

chore: update @pagopa/selfcare-common-frontend to version 1.34.72 in package.json and yarn.lock
