pagopa/selfcare-dashboard-frontend

- openApi/scripts/api-b4f-dashboard_fixPreGen.js
- package.json
- src/api/DashboardApiClient.ts
- src/hooks/__tests__/useTokenExchange.test.tsx
- src/hooks/useTokenExchange.ts
- src/pages/dashboardOverview/components/activeProductsSection/components/__tests__/ActiveProductCard.test.tsx
- src/services/__mocks__/tokenExchangeService.ts
- src/services/__tests__/tokenExchangeService.test.ts
- src/services/tokenExchangeService.ts
* SELC-1648 Swap to API which retrieves the entire url + consequent adaptation of the names of the methods to make them more speaking
* Fixed generated problem
* Fixed generated problem
* SELC-1648 Fixed unitTests
* temp commit
> SELC-1648 Using the API that retrieve complete url with also the token instead of the previous API that retrieve only the token

- src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
- src/pages/dashboard/components/dashboardSideMenu/DashboardSidenavItem.tsx
When clicking on a sidebar item other than overview, the selection also affected the submenu if it was open
Selecting the submenu does not also select other sidenav items
> Selecting the submenu does not also select other sidenav items

- src/locale/it.ts
- src/pages/dashboardTechnologyPartnerPage/DashboardTableContainer.tsx
- src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
- src/pages/dashboardTechnologyPartnerPage/TechnologyPartnerTable.tsx
Add missing filters table head in case of getTechnologyPartnersList api return empty
Add missing reset filters button from as in figma
Add missing divider above "See more" button
The page and the design on figma were different. Need to make changes to follow figma design.
Run application locally with mocked api getTechnologyPartnersList  to return or not a list
> SELC-2849 Add filter and graphic changes in dashboard

- src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
- src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx
Remove disable from filter button
Add disable on resetFilters button in case of initial state of form
Run application locally with mocked respones for the delegated service
> SELC-2849 remove disable buttons

- src/pages/dashboard/Dashboard.tsx
- src/pages/dashboardOverview/DashboardOverview.tsx
SELC-2970  fix
When the role in the product prod-io or prod-pagopa was operator and on another product was admin delegation section was visible
test locally with mock calls
> SELC-2970_hide delegation in case the product role is not admin

- src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
- src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
- src/services/__mocks__/partyService.ts
No popups when only have the exercise product + added mock case
It has been requested not to show the environment choice popup when added to the interoperability product only but to redirect directly to the operating product
With environment data and the added mock cases
> SELC-3034 No popups when only have the exercise product + added mock case

- src/pages/dashboardDelegations/__test__/DashboardDelegationsPage.test.tsx
- src/pages/dashboardOverview/__test__/DashboardOverview.test.tsx
- src/pages/dashboardOverview/components/activeProductsSection/ActiveProductsSection.tsx
- src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
- src/pages/dashboardTechnologyPartnerPage/__tests__/DashboardTablePT.test.tsx
- src/services/__mocks__/partyService.ts
- src/setupTests.ts
Release in UAT of ticket 3034 for showing popup in interop product only when operating product and environment product are available, in opposite case redirect directly to product back-office + unit test delegation page
Resolve the popup showed when a user is added only in interop operating product
Local with added mocks and with environment data api response
> SELC-3034 + unit test delegation page

- src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
- src/pages/dashboard/components/dashboardSideMenu/DashboardSidenavItem.tsx
SELC-3032 Delegation button in side menu should be in top level and be able to be hidden with arrow button
Added change as requested
Tested locally the app.
> SELC-3032 remove ability to hide delegation button in side menu

- src/hooks/useTokenExchange.ts
SELC 3122 add loading spinner for retrieveBackOfficeUrl Api call
When calling retrieveBackOfficeUrl  API there is a couple of seconds of delay with no feedback . Spinner added as feedback and to make the button unclickable again
Tested locally with mocked and integration testing with real api
> SELC 3122 add loading spinner for retrieveBackOfficeUrl Api call

- src/hooks/useTokenExchange.ts
SELC-3122 add loading spinner for retrieveBackOfficeUrl Api call
Added spinner feedback while waiting for retrieveBackOfficeUrl API and made it unable to click the button again while waiting.
> SELC-3122 add loading spinner for retrieveBackOfficeUrl Api call

- src/pages/dashboardOverview/components/notActiveProductsSection/NotActiveProductsSection.tsx
- src/services/__mocks__/partyService.ts
Check institution category and only allow categories L4, L6 and L45 to onboard to prod-io
Through the dashboard page it was possibile to bypass the BE checks for categories allowed to onboard in prod-pn
> [SELC-3459] fix: Allow onboarding to prod-pn only for some categories

- openApi/dashboard-api-docs.json
- openApi/generated-dashboard/dashboard-swagger20.json
- src/pages/dashboard/Dashboard.tsx
Once you select an Instititution of type PT you should be rendered in the "your institution page" not overview page
Remove required for manager in swagger
Tested in dev
> [SELC-3843] feat: Dynamic rendering of dashboard page for PT

- src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
Added missing event in onboarding io premiuim flow
Changed events called in wrong place.
Add missing properties in payload object
In order to follow the user jorney during onboarding to prod-io-premuim and to be able to track in through mix panel added events that can be traced in mix panel dashboard.
Tested locally
> [SELC-2278]: Feat: Integration with mix panel events for premium flow

- src/components/partySelectionSearch/PartyItemContainer.tsx
- src/components/partySelectionSearch/PartySelectionSearch.tsx
- src/components/partySelectionSearch/__tests__/PartySelectionSearch.test.tsx
Implemented lazy loading for institution logos.
The select institutions page was experiencing slow loading times due to the large number of institution logos being loaded synchronously. To address this issue and improve overall performance.
Tested locally and in dev
> [SELC-4661] Feat: Optimize rendering of select institutions page

- openApi/dashboard-api-docs.json
- openApi/generated-dashboard/dashboard-swagger20.json
- src/api/DashboardApiClient.ts
- src/services/tokenExchangeService.ts
Added v2 version of api retrieve backoffice
> Fix: Add retrieve backoffice to v2

- src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
- src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
Added link button for documentation
added unit test for link
To explain to the users how to delegate an institution a documentation page was created and a link was added that sends the user to that page
Tested locally and unit test
> [SELC-4779] Feat: Add link to how to delegate documentation

- src/api/__mocks__/DashboardApiClient.ts
- src/locale/it.ts
- src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
- src/pages/dashboardDelegationsAdd/components/CustomListBoxComponent.tsx
added custom listBoxComponent
handle filter logic of autocomplete by ra
Allow the user to search by fiscal code brokers in case the name of the instituion is missing.
Tested in local and with dev enviroment data.
> [SELC-4781] Feat: Add search by fiscal code of brokers

- src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
- Modified the Autocomplete component behavior to initiate filtering only after the user enters - 11 characters in the input field.
Previously, filtering occurred on any character input.
This change aims to improve the user experience by reducing unnecessary filtering and visual clutter when the user types short queries.
Manual testing was conducted to ensure the functionality
> [SELC-4781] Improve Autocomplete UX: Filter suggestions only after 11 characters

- src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
- src/pages/dashboardOverview/components/notActiveProductsSection/components/__tests__/NotActiveProductCard.test.tsx
[SELC-4969] Feat: dynamic query params for io premium
Following the new refactor in ms Onboarding it is necessary to send the partyId in place of externalId only for prod-io-premium
Tested in dev
[SELC-4969]: https://pagopa.atlassian.net/browse/SELC-4969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-4969] Feat: dynamic query params for io premium

- src/api/__mocks__/DashboardApiClient.ts
- src/locale/it.ts
- src/pages/dashboard/__tests__/Dashboard.test.tsx
- src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
- src/pages/dashboardOverview/components/notActiveProductsSection/__tests__/NotActiveProductsSection.test.tsx
- src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCard.tsx
- src/pages/dashboardTechnologyPartnerPage/__tests__/utils.test.ts
- src/services/__mocks__/productService.ts
- src/utils/helperFunctions.ts
Updated the text displayed on product cards in the "Active Products" section to indicate when a user does not have the role required to manage a product.
updated unit tests
This update improves clarity for users by clearly distinguishing between products they can manage and those they cannot. This distinction is crucial for effective product management and ensures that users are aware of their access limitations.
Tested by running the application in local and mocking a user without permissions on the product.
> [SELC-5583] Feat: Update Product Cards to Show Role-Based Management Status in Active Products Section

- src/components/DashboardHeader.tsx
- src/hooks/useProductsRolesMap.tsx
- src/pages/dashboard/Dashboard.tsx
Changed the list of products that are passed to user micro frontend by checking if the user is authorized to handle the users of that product.
To fix a bug where the /roles api was called for not authorized products leading in some cases like interop where the filters roles select would have extra options in user micro frontend
Tested by deploying the branch in dev
> [SELC-5780] Fix: call api /roles only for authorized products

- src/pages/dashboard/components/dashboardSideMenu/DashboardSideMenu.tsx
- src/services/__mocks__/partyService.ts
Added the new action Actions.ListProductUsers
adapted mocked data
To differentiate admin of the aggregator from the admin of the aggregated user.
Tested locally
> [SELC-5831] Feat: use ListProductUsers to handle users section visibility

- src/pages/dashboardTechnologyPartnerPage/TechPartnersTable.tsx
changed method of redirect from history to window object
The selected party on header does not refresh with history.push because the header comes from an external library
Tested locally
> [SELC-5822] fix: change method used for the redirect to refresh the selected party on header

- package.json
- src/components/partySelectionSearch/__tests__/PartySelectionSearch.test.tsx
- src/locale/de.ts
- src/locale/en.ts
- src/locale/fr.ts
- src/locale/sl.ts
- src/pages/dashboard/__tests__/Dashboard.test.tsx
- src/pages/dashboard/components/dashboardSideMenu/__test__/DashboardSideMenu.test.tsx
- src/pages/dashboardDelegationsAdd/components/__tests__/AddDelegationsForm.test.tsx
- src/pages/dashboardHandleDelegatesPage/__tests__/DashboardHandleDelegatesPage.test.tsx
- src/pages/dashboardHandleDelegatesPage/components/TableCellWithStyle.tsx
- src/pages/dashboardHandleDelegatesPage/components/TechPartnersTable.tsx
- src/pages/dashboardHandleDelegatesPage/components/TechnologyPartnerTable.tsx
- src/pages/dashboardHandleDelegatesPage/components/__tests__/DashboardTablePT.test.tsx
- src/pages/dashboardOverview/__tests__/DashboardOverview.test.tsx
- src/pages/dashboardOverview/components/activeProductsSection/components/__tests__/GenericEnvProductModal.test.tsx
- src/pages/dashboardOverview/components/activeProductsSection/components/__tests__/SessionModalInteropProduct.test.tsx
- src/pages/dashboardOverview/components/notActiveProductsSection/components/__tests__/NotActiveProductCard.test.tsx
- src/pages/dashboardOverview/components/partyCard/components/__tests__/GeoTaxonomySection.test.tsx
- src/pages/partySelectionContainer/partySelection/PartySelection.tsx
- yarn.lock
[SELC-6042] feat: Updated common-frontend library dependency for introduce language detection feature
[SELC-5867] Feat: map instituionRootName for aoo/ uo
[SELC-5941] Feat: Resolve vulnerability for node-fetch dependency
**Updated SelfCare translations Pt.2**
In order to introduce the language detection feature and release the worked features
Tested in dev environment ensuring that all the use case are satisfied
[SELC-6042]: https://pagopa.atlassian.net/browse/SELC-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5867]: https://pagopa.atlassian.net/browse/SELC-5867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5941]: https://pagopa.atlassian.net/browse/SELC-5941?atlOrigin=eyJpIjoiNWR …
> [SELC-6042] feat: Updated common-frontend library dependency for introduce language detection feature

- src/components/DashboardHeader.tsx
- src/pages/dashboardOverview/components/activeProductsSection/components/ActiveProductCardContainer.tsx
- src/services/__mocks__/productService.ts
add check for length of backOfficeEnvironmentConfigurations
The modal should not be visible if the backOfficeEnvironmentConfigurations is empty
Tested by mocking the bug in local enviroment and verying the fix
> [SELC-6105] Fix: add check for length of backOfficeEnvironmentConfigurations

- src/components/ProductNavigationBar.tsx
- src/locale/it.ts
- src/pages/dashboard/Dashboard.tsx
- src/pages/dashboardDelegations/DashboardDelegationsPage.tsx
- src/pages/dashboardDelegationsAdd/AddDelegationPage.tsx
- src/pages/dashboardDelegationsAdd/components/AddDelegationForm.tsx
- src/services/__mocks__/partyService.ts
- src/services/__mocks__/productService.ts
integrate ne action CreateDelegation
Hide add delegate button if no products can be delegated
hide specific add delegate button if that product can not be delegated
filter the list of delegable products in the form
update mockedData
The userRole ADMIN_EA_IO can see but not delegate a new partner. Add the new action to be able to distinguish who can see and who can delegate new partners.
> [SELC-6382] feat: integrate action CreateDelegation

- src/pages/dashboardOverview/components/notActiveProductsSection/components/NotActiveProductCardContainer.tsx
- src/pages/dashboardOverview/components/notActiveProductsSection/components/productFilters.ts
- src/utils/constants.ts
Add check for instituion type PSP
optimize code for not active product cards
The pagopa insights service is only avaible to psp institutions so the y can se transaction data.
> [SELC-6532] feat: Allow onboarding on pagoPA Insights only for psp

- src/hooks/__tests__/useProductRolesMap.test.tsx
- src/hooks/useProductsRolesMap.tsx
add exception for prod pagopa when caching roles configuration
prod pagoPa ha sifferent roles based on instituion type. When switching from two instituions that had prod-pagopa as a active product the FE would not refetch the roles as it was already cached.
> [SELC-6792] fix: fetch product roles for prod pagopa
